trigger:
- main

variables:
  azureServiceConnection: 'azurerm-terraform-backend'
  resourceGroup: 'rg-tfstate'
  storageAccount: 'tfstate7a4c4iw4gbetk'
  container: 'terraform-state'
  tfStateKey: 'petclinic.tfstate'

stages:

# =========================
# STAGE 1: TERRAFORM PLAN
# =========================
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: Plan
    displayName: 'Terraform Plan Job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: '$(azureServiceConnection)'
        backendAzureRmResourceGroupName: '$(resourceGroup)'
        backendAzureRmStorageAccountName: '$(storageAccount)'
        backendAzureRmContainerName: '$(container)'
        backendAzureRmKey: '$(tfStateKey)'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-out=main.tfplan'
        environmentServiceNameAzureRM: '$(azureServiceConnection)'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Terraform Plan'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)'
        artifact: 'terraform-plan'
        publishLocation: 'pipeline'

# =========================
# STAGE 2: TERRAFORM APPLY
# =========================
- stage: Deploy
  displayName: 'Terraform Apply'
  dependsOn: Plan
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to Production'
    environment: 'production'   #Manual approval happens here
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none

          - task: DownloadPipelineArtifact@2
            displayName: 'Download Terraform Plan'
            inputs:
              buildType: 'current'
              artifactName: 'terraform-plan'
              targetPath: '$(System.DefaultWorkingDirectory)'

          - task: TerraformInstaller@0
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: '$(azureServiceConnection)'
              backendAzureRmResourceGroupName: '$(resourceGroup)'
              backendAzureRmStorageAccountName: '$(storageAccount)'
              backendAzureRmContainerName: '$(container)'
              backendAzureRmKey: '$(tfStateKey)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              commandOptions: 'main.tfplan'
              environmentServiceNameAzureRM: '$(azureServiceConnection)'
